#워크폴로우 이름
name: CI

#워크플로우가 시작될 조건
on:
  pull_request:
    types: [closed]
  #workflow를 수동으로 실행 가능
  workflow_dispatch:

env:
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
  S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  CODE_DEPLOY_NAME: ${{ secrets.AWS_CODE_DEPLOY_APPLICATION_NAME }}
  CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest  #실행 환경 지정
    #실행 스텝 지정
    steps:
      - name: Code checkout
        id: checkout-code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: application.yml 파일 생성
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml

      - name: application-dev.yml 파일 생성
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml

      - name: application-temp.yml 파일 생성
        run: |
          cd ./src/main/resources
          touch ./application-temp.yml
          echo "${{ secrets.TEMP_APPLICATION_YML }}" > ./application-temp.yml

      - name: 빌드를 위한 MySQL 설정
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'tempDB'
          mysql user: 'temp'
          mysql password: ${{ secrets.TEMP_MYSQL_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR에 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ECR의 이미 업로드된 이미지 삭제
        run: |
          aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag="latest";

      - name: 도커이미지 빌드, 태그하고 ECR에 푸시
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          #도커 빌드
          docker build --no-cache -t $ECR_REPOSITORY:$IMAGE_TAG .
          #태그
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          #ECR에 푸시
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Code Deploy를 통해 배포
        run: |
          echo "Deploy to EC2"
          aws deploy create-deployment \
          --application-name $CODE_DEPLOY_NAME \
          --deployment-group-name $CODE_DEPLOY_GROUP \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}